# Controls when the workflow will run.
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: test1.nurseprofessors.com
        username: ${{ secrets.ftp_USERNAME }}
        password: ${{ secrets.ftp_PASSWORD }}
        server-dir: ./Understanding-postgresql/ #path to the directory containing the code to be uploaded.
        exclude: ".git/ .github/" #You can specify files/directory to exclude.